# Generated by Django 5.2.4 on 2025-07-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(choices=[('linkedin', 'LinkedIn'), ('twitter', 'Twitter')], max_length=50)),
                ('ai_model', models.CharField(choices=[('gemini', 'Gemini')], max_length=50)),
                ('prompt', models.TextField()),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('automation_result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
