# Generated by Django 5.2.4 on 2025-07-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='app',
            field=models.CharField(choices=[('linkedin', 'LinkedIn')], max_length=50),
        ),
    ]
