# Generated by Django 5.2.4 on 2025-07-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automator', '0002_task_is_posted_task_scheduled_time_alter_task_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_posted',
        ),
        migrations.RemoveField(
            model_name='task',
            name='scheduled_time',
        ),
        migrations.AlterField(
            model_name='task',
            name='ai_model',
            field=models.CharField(choices=[('gpt', 'GPT'), ('gemini', 'Gemini')], max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='app',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('instagram', 'Instagram')], max_length=50),
        ),
    ]
